name: "Jonathan O'Dea"
favicon: null
layout_spectrum: 0.5031697659287602
typography_spectrum: 0.07305347407236695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111723'
    - '#548af0'
    - '#dbe7f5'
    - '#4b576f'
    - '#e45f74'
  brandStrength: 0.25
  lightness: 0.6711588015314192
  saturation: 0.5
  rhythmicContrast: 0.7735505958553404
purpose: []
